from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.core.validators import validate_email, RegexValidator
from django_unixdatetimefield import UnixDateTimeField

from .managers import UserManager
from django.conf import settings


# fields in model will use camel case so django can parse json which is also camel case
class AbstractMapping(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        db_column='user_id'
    )
    created = UnixDateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ProfileId(AbstractMapping):
    profile_id = models.CharField(primary_key=True, max_length=200)

    class Meta:
        db_table = 'user_profile_id'


class ProviderProfileId(AbstractMapping):
    provider_profile_id = models.CharField(primary_key=True, max_length=200)

    class Meta:
        db_table = 'user_provider_profile_id'


class ApplicationId(AbstractMapping):
    application_id = models.CharField(primary_key=True, max_length=200)

    class Meta:
        db_table = 'user_application_id'


class LocationId(AbstractMapping):
    # type location_id as UUIDField and make it editable so it can be saved from UI
    # if editable=false, then we cannot set uuid from UI and uuid has to be generated by MYSQL, we don't want this
    location_id = models.CharField(primary_key=True, max_length=32, editable=True)

    class Meta:
        db_table = 'user_location_id'


class JobPostId(AbstractMapping):
    job_post_id = models.CharField(primary_key=True, max_length=200)

    class Meta:
        db_table = 'user_job_post_id'


class Role(AbstractMapping):
    role = models.CharField(null=True, blank=True, max_length=200)

    class Meta:
        db_table = 'user_role'


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        db_table = 'user'

    # validators
    phone_validator = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                     message="Phone number format: '+999999999'. Max 15# allowed.")
    user_id = models.CharField(primary_key=True, max_length=40, null=False, blank=False)
    first_name = models.CharField(_('first name'), max_length=30, null=True, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, null=True, blank=True)
    email = models.EmailField(_('email address'), validators=[validate_email, ])
    phone = models.CharField(validators=[phone_validator, ], max_length=15, null=True, blank=True)
    # not considering provider profile for now, assume all users are seekers
    active_profile_id = models.CharField(max_length=200, null=True, blank=True)
    active_provider_profile_id = models.CharField(max_length=200, null=True, blank=True)
    active_location_id = models.CharField(max_length=200, null=True, blank=True)
    active = models.BooleanField(_('active'), default=True)

    created = UnixDateTimeField(null=True, blank=True)
    modified = UnixDateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
