# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 04:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=30, null=True, verbose_name='first name')),
                ('lastName', models.CharField(max_length=30, null=True, verbose_name='last name')),
                ('userId', models.CharField(max_length=30, unique=True, verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profileIds', models.CharField(max_length=4000, null=True)),
                ('activeProfileId', models.CharField(max_length=32, null=True)),
                ('locationIds', models.CharField(max_length=4000, null=True)),
                ('activeLocationId', models.CharField(max_length=32, null=True)),
                ('applicationIds', models.CharField(max_length=4000, null=True)),
                ('roles', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
