# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:21
from __future__ import unicode_literals

from django.db import migrations
import userapp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userapp.managers.UserManager()),
            ],
        ),
    ]
