# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 02:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_app.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userId', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, verbose_name='_user_id')),
                ('firstName', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Max 15# allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('roles', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationId',
            fields=[
                ('applicationId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPostId',
            fields=[
                ('jobPostId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationId',
            fields=[
                ('locationId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileId',
            fields=[
                ('profileId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderProfileId',
            fields=[
                ('providerProfileId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='activeLocationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_app.LocationId'),
        ),
        migrations.AddField(
            model_name='user',
            name='activeProfileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_app.ProfileId'),
        ),
        migrations.AddField(
            model_name='user',
            name='activeProviderProfileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_app.ProviderProfileId'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
